from __future__ import annotations

import json
import shlex
from pathlib import Path

from .models import RepoSnapshot


PYTHON_SYNTAX_HELPER = """from __future__ import annotations

import ast
import sys
from pathlib import Path

SKIP = {".git", ".hg", ".svn", "node_modules", "vendor", ".venv", "venv", "dist", "build", "__pycache__"}


def main() -> int:
    root = Path(sys.argv[1] if len(sys.argv) > 1 else ".").resolve()
    failures = []
    checked = 0
    for path in root.rglob("*.py"):
        if any(part in SKIP for part in path.parts):
            continue
        try:
            text = path.read_text(encoding="utf-8", errors="strict")
            ast.parse(text, filename=str(path))
            checked += 1
        except (OSError, UnicodeError, SyntaxError) as exc:
            failures.append(f"{path}: {exc}")
    print(f"Python syntax files checked: {checked}")
    if failures:
        print("\\n".join(failures), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
"""


def build_test_harness(snapshot: RepoSnapshot, commands: list[dict[str, object]]) -> dict[str, object]:
    test_commands = [item for item in commands if item.get("kind") == "test"]
    generated_files: list[dict[str, str]] = []
    static_checks: list[str] = []

    if "Python" in snapshot.languages:
        generated_files.append({
            "path": "python_syntax_check.py",
            "purpose": "Parse Python source with ast without importing or executing repository modules.",
            "content": PYTHON_SYNTAX_HELPER,
        })
        static_checks.append('python "$HARNESS_DIR/python_syntax_check.py" "$REPO_ROOT"')

    if snapshot.test_files and test_commands:
        status = "existing-tests"
    elif static_checks:
        status = "generated-minimum"
    else:
        status = "blocked"

    limitations = [
        "Static syntax checks do not prove behavioral equivalence.",
        "Discovered repository commands may execute arbitrary project code and are never auto-run by ModFactory.",
        "Behavioral characterization tests still require domain-specific assertions when current coverage is missing.",
    ]
    if not snapshot.test_files:
        limitations.insert(0, "No existing automated tests were detected; the generated harness is only a minimum safety scaffold.")

    return {
        "status": status,
        "requires_human_review": True,
        "auto_executes_project_code": False,
        "recommended_commands": test_commands,
        "generated_files": generated_files,
        "static_checks": static_checks,
        "limitations": limitations,
        "approval_rule": "Review discovered commands and run them only in a trusted local or sandboxed environment.",
    }


def render_baseline_script(harness: dict[str, object]) -> str:
    lines = [
        "#!/usr/bin/env sh",
        "set -eu",
        "",
        "# Generated by ModFactory.",
        "# This script intentionally runs only generated static checks.",
        "# It does NOT execute build/test commands discovered from the target repository.",
        "",
        'REPO_ROOT="."',
        'if [ "$#" -ge 1 ]; then REPO_ROOT="$1"; fi',
        'HARNESS_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"',
        "",
    ]
    for command in harness.get("static_checks", []):
        lines.append(str(command))

    recommended = harness.get("recommended_commands", [])
    lines.extend(["", "# Discovered project commands (review before running):"])
    if recommended:
        for item in recommended:
            command = shlex.quote(str(item.get("command", "")))
            source = str(item.get("source", "unknown")).replace("\n", " ")
            lines.append(f"# {source}: {command}")
    else:
        lines.append("# none")

    lines.append("")
    return "\n".join(lines)


def write_harness_files(harness: dict[str, object], out_dir: str | Path) -> tuple[Path, Path]:
    out = Path(out_dir)
    harness_dir = out / "harness"
    harness_dir.mkdir(parents=True, exist_ok=True)

    json_path = harness_dir / "harness.json"
    script_path = harness_dir / "baseline.sh"
    json_path.write_text(json.dumps(harness, indent=2), encoding="utf-8")
    script_path.write_text(render_baseline_script(harness), encoding="utf-8")

    for item in harness.get("generated_files", []):
        path = harness_dir / str(item["path"])
        path.write_text(str(item["content"]), encoding="utf-8")

    return json_path, script_path
